{% set version = "1.2.1" %}

package:
  name: biotraj
  version: {{ version }}

source:
  url: https://github.com/biotite-dev/biotraj/archive/v{{ version }}.tar.gz
  sha256: 4c93641dfa138d067be8d3aeb8f07be6342ec76d450ad3ab1801a92bfdbfbf85

build:
  number: 1
  script:
    - export SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}  # [not win]
    - set SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}     # [win]
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py < 310]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=3.0                           # [build_platform != target_platform]
    - numpy >=2.0                            # [build_platform != target_platform]
    - {{ stdlib("c") }}
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
  host:
    - python
    - pip
    - setuptools >=64
    - setuptools_scm >=8
    - wheel >=0.30
    - cython >=3.0
    - numpy >=2.0
  run:
    - python
    - numpy >=1.26
    - scipy >=1.13

test:
  source_files:
    - tests/
  requires:
    - pytest
    - netcdf4
  commands:
    - pytest

about:
  home: https://github.com/biotite-dev/biotraj/
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: LICENSE.rst
  summary: The package is internally used by https://github.com/biotite-dev/biotite
  dev_url: https://github.com/biotite-dev/biotraj

extra:
  recipe-maintainers:
    - padix-key
    - JHKru
